#sdk: "/Users/lars/.rvm/gems/ruby-1.9.3-p327/gems/rhodes-3.5.1.12"
sdkversion: 3.5.0
name: store-rhodes
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.store-rhodes
  BundleURLScheme: store-rhodes
wp:
  productid: '1e3cec70-255d-0130-4a1d-482a141043d9'
symbian:
  uid: '0xeb4aeb04'
android:
  version: 2.1

extensions: ["json", "rhoconnect-client", "rhoconnect-push"]
